def match_query(match_id: int) -> str:
    return f"""{{
      match(id: {match_id}){{
        actualRank
        averageImp
        averageRank
        analysisOutcome
        bracket
        bottomLaneOutcome
        barracksStatusDire
        barracksStatusRadiant
        clusterId
        direKills
        didRadiantWin
        durationSeconds
        endDateTime
        firstBloodTime
        gameMode
        isStats
        laneReport{{
          radiant{{
            midLane{{
              denyCount
              meleeCount
              neutralCount
              rangeCount
              siegeCount
            }}
            offLane{{
              denyCount
              meleeCount
              neutralCount
              siegeCount
            }}
            safeLane{{
              denyCount
              meleeCount
              neutralCount
              siegeCount
            }}
          }}
          dire{{
            midLane{{
              denyCount
              meleeCount
              neutralCount
              rangeCount
              siegeCount
            }}
            offLane{{
              denyCount
              meleeCount
              neutralCount
              siegeCount
            }}
            safeLane{{
              denyCount
              meleeCount
              neutralCount
              siegeCount
            }}
          }}
        }}
        lobbyType
        midLaneOutcome
        numHumanPlayers
        players{{
          award
        }}
        pickBans{{
          adjustedWinRate
          bannedHeroId
          baseWinRate
          heroId
          isPick
          isRadiant
          isCaptain
          letter
          order
          playerIndex
          wasBannedSuccessfully
        }}
        playbackData{{
          buildingEvents{{
            didShrineActivate
            hp
            indexId
            isRadiant
            maxHp
            npcId
            positionX
            positionY
            time
            type
          }}
          runeEvents{{
            action
            indexId
            location
            positionX
            positionY
            rune
            time
          }}
          roshanEvents{{
            x
            y
          }}
          towerDeathEvents{{
            radiant
            dire
          }}
          wardEvents{{
            action
            fromPlayer
            indexId
            positionX
            positionY
            playerDestroyed
            time
            wardType
          }}
        }}
        rank
        regionId
        replaySalt
        radiantKills
        radiantNetworthLeads
        radiantExperienceLeads
        sequenceNum
        topLaneOutcome
        towerStatus{{
          outposts{{
            isRadiantSide
            isControlledByRadiant
            npcId
          }}
          towers{{
            hp
            npcId
          }}
        }}
        towerDeaths{{
          attacker
          isRadiant
          npcId
          time
        }}
        winRates
      }}
    }}
    """


def matches_query(match_ids: list[int]) -> str:
    return f"""{{
      matches(ids: {match_ids}){{
        actualRank
        averageImp
        averageRank
        analysisOutcome
        bracket
        bottomLaneOutcome
        barracksStatusDire
        barracksStatusRadiant
        clusterId
        direKills
        didRadiantWin
        durationSeconds
        endDateTime
        firstBloodTime
        gameMode
        isStats
        laneReport{{
          radiant{{
            midLane{{
              denyCount
              meleeCount
              neutralCount
              rangeCount
              siegeCount
            }}
            offLane{{
              denyCount
              meleeCount
              neutralCount
              siegeCount
            }}
            safeLane{{
              denyCount
              meleeCount
              neutralCount
              siegeCount
            }}
          }}
          dire{{
            midLane{{
              denyCount
              meleeCount
              neutralCount
              rangeCount
              siegeCount
            }}
            offLane{{
              denyCount
              meleeCount
              neutralCount
              siegeCount
            }}
            safeLane{{
              denyCount
              meleeCount
              neutralCount
              siegeCount
            }}
          }}
        }}
        lobbyType
        midLaneOutcome
        numHumanPlayers
        players{{
          award
        }}
        pickBans{{
          adjustedWinRate
          bannedHeroId
          baseWinRate
          heroId
          isPick
          isRadiant
          isCaptain
          letter
          order
          playerIndex
          wasBannedSuccessfully
        }}
        playbackData{{
          buildingEvents{{
            didShrineActivate
            hp
            indexId
            isRadiant
            maxHp
            npcId
            positionX
            positionY
            time
            type
          }}
          runeEvents{{
            action
            indexId
            location
            positionX
            positionY
            rune
            time
          }}
          roshanEvents{{
            x
            y
          }}
          towerDeathEvents{{
            radiant
            dire
          }}
          wardEvents{{
            action
            fromPlayer
            indexId
            positionX
            positionY
            playerDestroyed
            time
            wardType
          }}
        }}
        rank
        regionId
        replaySalt
        radiantKills
        radiantNetworthLeads
        radiantExperienceLeads
        sequenceNum
        topLaneOutcome
        towerStatus{{
          outposts{{
            isRadiantSide
            isControlledByRadiant
            npcId
          }}
          towers{{
            hp
            npcId
          }}
        }}
        towerDeaths{{
          attacker
          isRadiant
          npcId
          time
        }}
        winRates
      }}
    }}
    """
