HEROES = {
    "Anti-Mage": "antimage",
    "Shadow Fiend": "nevermore",
    "Vengeful Spirit": "vengefulspirit",
    "Windranger": "windrunner",
    "Zeus": "zuus",
    "Necrophos": "necrolyte",
    "Queen of Pain": "queenofpain",
    "Wraith King": "wraith_king",
    "Clockwerk": "clockwerk",
    "Nature's Prophet": "nature's_prophet",
    "Lifestealer": "lifestealer",
    "Doom": "doom",
    "Outworld Destroyer": "obsidian_destroyer",
    "Treant Protector": "treant",
    "Io": "wisp",
    "Centaur Warrunner": "centaur",
    "Magnus": "magntaur",
    "Timbersaw": "shredder",
    "Underlord": "abyssal_underlord",
}
